---
- hosts: loadbalancers
  become: true
  tasks:
    - service: name=nginx state=stopped
    - wait_for: port=80 state=drained

- hosts: webservers
  become: true
  tasks:
    - service: name=apache2 state=stopped
    - wait_for: port=80 state=stopped

- hosts: databases
  become: true
  tasks:
    - service: name=mysql state=restarted

- hosts: webservers
  become: true
  tasks:
    - service: name=apache2 state=started

- hosts: loadbalancers
  become: true
  tasks:
    - service: name=nginx state=started
