---
- hosts: webservers
  become: true
  tasks:

    - name: install apache2
      apt: name=libapache2-mod-wsgi-py3 state=absent update_cache=yes

    - name: install apache2
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-virtualenv
        - python-mysqldb
        - python-httplib2

    - name: ensure apache2 started and enabled
      service: name=apache2 state=started enabled=yes

    - name: ensure apache wsgi module enabled
      apache2_module: name=wsgi state=present
      notify: restart apache

    - name: copy demo app source
      copy: src=demo/app/ dest=/var/www/demo mode=0755
      notify: restart apache

    - name: copy apache
      copy: src=demo/demo.conf dest=/etc/apache2/sites-available mode=0755
      notify: restart apache

    - name: set python virtual env
      pip: requirements=/var/www/demo/requirements.txt virtualenv=/var/www/demo/.venv
      notify: restart apache

    - name: disable apache default site
      file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
      notify: restart apache

    - name: enable demo apache site
      file: src=/etc/apache2/sites-available/demo.conf dest=/etc/apache2/sites-enabled/demo.conf state=link
      notify: restart apache

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
